name: GitHub action info
## Simply display some inner variable information from github actions

on:
  push:
    branches:
      - main
    tags:
      - v[0-9]+.[0-9]+**

jobs:
  show_info:
    runs-on: ubuntu-latest
    steps:
      - name: Push main info vars
        run: |
          echo github.base_ref: ${{ github.base_ref }}
          echo github.head_ref: ${{ github.head_ref }}
          echo github.ref: ${{ github.ref }}
          echo github.ref_name: ${{ github.ref_name }}
          echo github.ref_type: ${{ github.ref_type }}
          echo github.event_name: ${{ github.event_name }}
          echo github.event.head_commit.message: ${{ github.event.head_commit.message }}
          echo github.sha: ${{ github.sha }}
          echo branch of github.sha: $(git branch -r -a --contains "${{ github.sha }}" | grep -v detached | tr -d "*" | tr -s " ")
          echo branch of github.sha - raw: $(git branch -r -a --contains "${{ github.sha }}")
      # - name: Dump GitHub context
      #   env:
      #     GITHUB_CONTEXT: ${{ toJson(github) }}
      #   run: echo "$GITHUB_CONTEXT"
  if_test1:
    runs-on: ubuntu-latest
    if: |
      github.ref == 'refs/heads/main'
    steps:
      - name: Result
        run: echo "If main branch success! (${{ github.job }})"
  if_test2:
    runs-on: ubuntu-latest
    if: |
      github.ref == 'refs/heads/main' &&
      contains(github.event.head_commit.message, 'merge')
    steps:
      - name: Result
        run: echo "Multi-if && success! (${{ github.job }})"
  if_test2b:
    runs-on: ubuntu-latest
    if: |
      github.ref == 'refs/heads/main' &&
      (
        contains(github.event.head_commit.message, 'Merge') ||
        contains(github.event.head_commit.message, 'merge')
      )
    steps:
      - name: Result
        run: echo "Multi-if && success! (${{ github.job }})"
  if_test3:
    runs-on: ubuntu-latest
    if: |
      github.ref == 'refs/heads/main' ||
      contains(github.event.head_commit.message, 'merge')
    steps:
      - name: Result
        run: echo "Multi-if || success! (${{ github.job }})"
  if_test4:
    runs-on: ubuntu-latest
    if: |
      github.ref == 'refs/heads/main' &&
      startsWith(github.event.head_commit.message, 'random')
    steps:
      - name: Result
        run: echo "Multi-if && startsWith success! (${{ github.job }})"
  if_test5:
    runs-on: ubuntu-latest
    if: github.ref_type == 'tag'
    steps:
      - name: Result
        if: contains($(git branch -r -a --contains "${{ github.sha }}" | grep -v detached | tr -d "*" | tr -s " "), "main")
        run: |
          echo "separated-if, tag type and main branch success! (${{ github.job }})"
          echo "github.ref_type: ${{ github.ref_type }}"
          echo git branch -r -a --contains ...: $(git branch -r -a --contains "${{ github.sha }}")
  if_test5a:
    runs-on: ubuntu-latest
    if: ${{ github.ref_type == 'tag' }} && $(git branch -r -a --contains "${{ github.sha }}" | grep -v detached | grep "main")
    steps:
      - name: Result
        run: |
          echo "Multi-if && tag type, check branch success! (${{ github.job }})"
          echo "github.ref_type: ${{ github.ref_type }}"
          echo git branch -r -a --contains ...: $(git branch -r -a --contains "${{ github.sha }}")
  if_test5b:
    runs-on: ubuntu-latest
    if: github.ref_type == 'tag'
    if: contains($(git branch -r -a --contains "${{ github.sha }}" | grep -v detached | tr -d "*" | tr -s " "), "main"))
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: '0'
      - name: Result
        run: |
          echo "Multi-if && tag type, check branch with checkout success! (${{ github.job }})"
          echo "github.ref_type: ${{ github.ref_type }}"
          echo git branch -r -a --contains ...: $(git branch -r -a --contains "${{ github.sha }}")
